# Generated by Django 6.0.6 on 2026-07-03 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0002_purchase_gst_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseitem',
            name='barcode',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='gst_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='unit',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
