# Generated by Django 6.0.6 on 2026-07-04 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0003_purchaseitem_barcode_purchaseitem_gst_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseitem',
            name='product_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
