# Generated by Django 6.0.6 on 2026-07-06 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0004_purchaseitem_product_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='gst_percentage',
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='gst_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
