# Generated by Django 6.0.6 on 2026-06-30 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('owner_name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='business/logo/')),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('currency_symbol', models.CharField(default='₹', max_length=5)),
                ('timezone', models.CharField(default='Asia/Kolkata', max_length=100)),
                ('gst_enabled', models.BooleanField(default=False)),
                ('gst_number', models.CharField(blank=True, max_length=20)),
                ('barcode_enabled', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
