# Generated by Django 6.0.6 on 2026-06-30 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='timezone',
        ),
        migrations.AlterModelTable(
            name='business',
            table='business',
        ),
    ]
